import type { Quote, Booking, Testimonial } from '@/types'

// Consistent mock data used across all admin pages
// Names, events, and dates are shared so the admin feels like a real system

export const MOCK_QUOTES: Quote[] = [
  {
    id: 'q1',
    name: 'Jake Morrison',
    email: 'jake.morrison@gmail.com',
    phone: '(702) 555-1234',
    event_type: 'Bachelor Party',
    preferred_vehicle_id: '1',
    event_date: '2026-03-14',
    pickup_time: '20:00',
    guest_count: 22,
    duration_hours: 5,
    pickup_location: 'MGM Grand',
    dropoff_location: 'Encore at Wynn',
    details: 'Bachelor party for my brother. Looking for the full nightlife experience — clubs, maybe a strip club stop. Group of 22 guys flying in from Chicago.',
    status: 'new',
    quoted_amount: null,
    admin_notes: null,
    created_at: '2026-02-25T14:30:00Z',
    updated_at: '2026-02-25T14:30:00Z',
  },
  {
    id: 'q2',
    name: 'Rachel Kim',
    email: 'rachel.k@outlook.com',
    phone: '(310) 555-8901',
    event_type: 'Bachelorette Party',
    preferred_vehicle_id: '2',
    event_date: '2026-03-21',
    pickup_time: '19:00',
    guest_count: 15,
    duration_hours: 4,
    pickup_location: 'Cosmopolitan',
    dropoff_location: 'Cosmopolitan',
    details: 'Bachelorette party for my best friend! Want to hit Marquee and Omnia. Pink lighting if possible!',
    status: 'contacted',
    quoted_amount: null,
    admin_notes: 'Called back on 2/24. She wants pink theme. Checking availability for Crown Jewel.',
    created_at: '2026-02-23T10:15:00Z',
    updated_at: '2026-02-24T16:00:00Z',
  },
  {
    id: 'q3',
    name: 'David & Sarah Chen',
    email: 'dchen.wedding@gmail.com',
    phone: '(702) 555-4567',
    event_type: 'Wedding',
    preferred_vehicle_id: '4',
    event_date: '2026-04-05',
    pickup_time: '14:00',
    guest_count: 8,
    duration_hours: 6,
    pickup_location: 'Chapel of the Flowers',
    dropoff_location: 'Bellagio',
    details: 'Wedding ceremony at 2pm, reception at Bellagio at 5pm. Need transportation for bridal party of 8. Want photos at the Welcome to Las Vegas sign.',
    status: 'quoted',
    quoted_amount: 1200,
    admin_notes: 'Sent quote for The Monarch — 6 hours @ $150/hr + $300 photo stop package. Wedding special discount applied.',
    created_at: '2026-02-20T09:00:00Z',
    updated_at: '2026-02-22T11:30:00Z',
  },
  {
    id: 'q4',
    name: 'Marcus Thompson',
    email: 'marcus.t@corporateevents.com',
    phone: '(212) 555-7890',
    event_type: 'Corporate Event',
    preferred_vehicle_id: '3',
    event_date: '2026-03-10',
    pickup_time: '17:30',
    guest_count: 12,
    duration_hours: 4,
    pickup_location: 'Las Vegas Convention Center',
    dropoff_location: 'Caesars Palace',
    details: 'CES after-party client dinner. Need something upscale and professional. 12 executives.',
    status: 'booked',
    quoted_amount: 900,
    admin_notes: 'Booked Royal Sprinter. Corp billing approved. W-9 sent. Deposit received 2/18.',
    created_at: '2026-02-15T08:45:00Z',
    updated_at: '2026-02-18T14:20:00Z',
  },
  {
    id: 'q5',
    name: 'Amanda Reyes',
    email: 'amanda.r@yahoo.com',
    phone: '(702) 555-2345',
    event_type: 'Birthday Celebration',
    preferred_vehicle_id: '1',
    event_date: '2026-03-08',
    pickup_time: '21:00',
    guest_count: 28,
    duration_hours: 5,
    pickup_location: 'Aria Resort',
    dropoff_location: 'Aria Resort',
    details: 'My 30th birthday! Want to go all out. Club crawl with XS, Hakkasan, and maybe Omnia. Need the biggest bus.',
    status: 'booked',
    quoted_amount: 1500,
    admin_notes: 'Booked The Sovereign. Birthday package with champagne. Deposit paid. VIP entry at XS confirmed.',
    created_at: '2026-02-10T16:20:00Z',
    updated_at: '2026-02-12T10:00:00Z',
  },
  {
    id: 'q6',
    name: 'Tyler Brooks',
    email: 'tyler.brooks@gmail.com',
    phone: '(480) 555-6789',
    event_type: 'Nightlife & Club Crawl',
    preferred_vehicle_id: '2',
    event_date: '2026-03-07',
    pickup_time: '22:00',
    guest_count: 18,
    duration_hours: 4,
    pickup_location: 'Venetian',
    dropoff_location: 'Venetian',
    details: 'Group of college buddies hitting the clubs. Want to go to Omnia and Drai\'s.',
    status: 'completed',
    quoted_amount: 1000,
    admin_notes: 'Completed. Great group. Left 20% tip. Will send review request.',
    created_at: '2026-02-01T12:00:00Z',
    updated_at: '2026-03-08T02:00:00Z',
  },
  {
    id: 'q7',
    name: 'Emily Watson',
    email: 'emily.w@gmail.com',
    phone: '(702) 555-3456',
    event_type: 'Prom & Homecoming',
    preferred_vehicle_id: '5',
    event_date: '2026-05-16',
    pickup_time: '17:00',
    guest_count: 8,
    duration_hours: 5,
    pickup_location: '4521 Desert Inn Rd',
    dropoff_location: '4521 Desert Inn Rd',
    details: 'Prom night for my daughter and her friends. 8 students. Need pickup at home for photos, then to Centennial HS, then dinner at Maggiano\'s.',
    status: 'new',
    quoted_amount: null,
    admin_notes: null,
    created_at: '2026-02-26T08:00:00Z',
    updated_at: '2026-02-26T08:00:00Z',
  },
  {
    id: 'q8',
    name: 'Robert & Lisa Hayes',
    email: 'hayesfamily@gmail.com',
    phone: '(702) 555-9012',
    event_type: 'Airport Transfer',
    preferred_vehicle_id: '3',
    event_date: '2026-03-15',
    pickup_time: '11:00',
    guest_count: 6,
    duration_hours: 2,
    pickup_location: 'Harry Reid International Airport',
    dropoff_location: 'Bellagio',
    details: 'Family arriving for spring break. 6 people, 8 bags. Want a comfortable ride to the hotel.',
    status: 'quoted',
    quoted_amount: 350,
    admin_notes: 'Quoted Royal Sprinter for airport pickup. Sent quote via email.',
    created_at: '2026-02-22T15:00:00Z',
    updated_at: '2026-02-23T09:00:00Z',
  },
  {
    id: 'q9',
    name: 'Brianna Foster',
    email: 'bri.foster@hotmail.com',
    phone: '(619) 555-4321',
    event_type: 'Bachelorette Party',
    preferred_vehicle_id: '6',
    event_date: '2026-04-18',
    pickup_time: '20:00',
    guest_count: 35,
    duration_hours: 6,
    pickup_location: 'Wynn Las Vegas',
    dropoff_location: 'Wynn Las Vegas',
    details: 'Huge bachelorette party! 35 girls. Need the biggest bus. Pool party during the day, clubs at night.',
    status: 'new',
    quoted_amount: null,
    admin_notes: null,
    created_at: '2026-02-26T11:00:00Z',
    updated_at: '2026-02-26T11:00:00Z',
  },
  {
    id: 'q10',
    name: 'Derek Nguyen',
    email: 'derek.n@techcorp.io',
    phone: '(415) 555-8765',
    event_type: 'Las Vegas Strip Tour',
    preferred_vehicle_id: '2',
    event_date: '2026-03-22',
    pickup_time: '18:00',
    guest_count: 16,
    duration_hours: 3,
    pickup_location: 'Planet Hollywood',
    dropoff_location: 'Planet Hollywood',
    details: 'Team outing for our sales team. 16 people. Want a Strip tour with photo stops and maybe end at a nice restaurant.',
    status: 'cancelled',
    quoted_amount: 750,
    admin_notes: 'Client cancelled — dates changed for their conference.',
    created_at: '2026-02-05T10:30:00Z',
    updated_at: '2026-02-19T12:00:00Z',
  },
]

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'b1',
    quote_id: 'q4',
    client_name: 'Marcus Thompson',
    client_email: 'marcus.t@corporateevents.com',
    client_phone: '(212) 555-7890',
    event_type: 'Corporate Event',
    vehicle_id: '3',
    booking_date: '2026-03-10',
    start_time: '17:30',
    end_time: '21:30',
    duration_hours: 4,
    pickup_location: 'Las Vegas Convention Center',
    dropoff_location: 'Caesars Palace',
    guest_count: 12,
    total_amount: 900,
    deposit_amount: 350,
    deposit_paid: true,
    status: 'confirmed',
    notes: 'Corp billing approved. W-9 sent. VIP treatment for executives.',
    created_at: '2026-02-18T14:20:00Z',
    updated_at: '2026-02-18T14:20:00Z',
  },
  {
    id: 'b2',
    quote_id: 'q5',
    client_name: 'Amanda Reyes',
    client_email: 'amanda.r@yahoo.com',
    client_phone: '(702) 555-2345',
    event_type: 'Birthday Celebration',
    vehicle_id: '1',
    booking_date: '2026-03-08',
    start_time: '21:00',
    end_time: '02:00',
    duration_hours: 5,
    pickup_location: 'Aria Resort',
    dropoff_location: 'Aria Resort',
    guest_count: 28,
    total_amount: 1500,
    deposit_amount: 500,
    deposit_paid: true,
    status: 'deposit_paid',
    notes: 'Birthday package with champagne. VIP entry at XS confirmed.',
    created_at: '2026-02-12T10:00:00Z',
    updated_at: '2026-02-12T10:00:00Z',
  },
  {
    id: 'b3',
    quote_id: null,
    client_name: 'Jordan & Mike Patel',
    client_email: 'jpatel.wedding@gmail.com',
    client_phone: '(702) 555-1111',
    event_type: 'Wedding',
    vehicle_id: '4',
    booking_date: '2026-03-15',
    start_time: '13:00',
    end_time: '19:00',
    duration_hours: 6,
    pickup_location: 'The Venetian Chapel',
    dropoff_location: 'Caesars Palace',
    guest_count: 10,
    total_amount: 1100,
    deposit_amount: 400,
    deposit_paid: true,
    status: 'confirmed',
    notes: 'Photo stop at Welcome sign. Champagne toast after ceremony.',
    created_at: '2026-02-05T09:00:00Z',
    updated_at: '2026-02-08T11:00:00Z',
  },
  {
    id: 'b4',
    quote_id: null,
    client_name: 'Chris Rodriguez',
    client_email: 'chris.rod@gmail.com',
    client_phone: '(702) 555-2222',
    event_type: 'Bachelor Party',
    vehicle_id: '6',
    booking_date: '2026-03-14',
    start_time: '20:00',
    end_time: '03:00',
    duration_hours: 7,
    pickup_location: 'Mandalay Bay',
    dropoff_location: 'Mandalay Bay',
    guest_count: 38,
    total_amount: 2800,
    deposit_amount: 1000,
    deposit_paid: true,
    status: 'deposit_paid',
    notes: 'Large bachelor party. The Empire bus. Full club crawl: XS, Hakkasan, Omnia.',
    created_at: '2026-01-28T15:00:00Z',
    updated_at: '2026-02-02T10:00:00Z',
  },
  {
    id: 'b5',
    quote_id: 'q6',
    client_name: 'Tyler Brooks',
    client_email: 'tyler.brooks@gmail.com',
    client_phone: '(480) 555-6789',
    event_type: 'Nightlife & Club Crawl',
    vehicle_id: '2',
    booking_date: '2026-03-07',
    start_time: '22:00',
    end_time: '02:00',
    duration_hours: 4,
    pickup_location: 'Venetian',
    dropoff_location: 'Venetian',
    guest_count: 18,
    total_amount: 1000,
    deposit_amount: 400,
    deposit_paid: true,
    status: 'completed',
    notes: 'Completed successfully. Great group. Left 20% tip.',
    created_at: '2026-02-05T12:00:00Z',
    updated_at: '2026-03-08T02:00:00Z',
  },
  {
    id: 'b6',
    quote_id: null,
    client_name: 'Nicole Alvarez',
    client_email: 'nicole.a@gmail.com',
    client_phone: '(702) 555-3333',
    event_type: 'Bachelorette Party',
    vehicle_id: '2',
    booking_date: '2026-03-21',
    start_time: '19:00',
    end_time: '23:00',
    duration_hours: 4,
    pickup_location: 'Park MGM',
    dropoff_location: 'Park MGM',
    guest_count: 16,
    total_amount: 1000,
    deposit_amount: 400,
    deposit_paid: false,
    status: 'pending',
    notes: 'Awaiting deposit payment. Follow up by 3/1.',
    created_at: '2026-02-20T14:00:00Z',
    updated_at: '2026-02-20T14:00:00Z',
  },
  {
    id: 'b7',
    quote_id: null,
    client_name: 'Ryan Blackwell',
    client_email: 'ryan.b@gmail.com',
    client_phone: '(702) 555-4444',
    event_type: 'Airport Transfer',
    vehicle_id: '3',
    booking_date: '2026-03-01',
    start_time: '10:00',
    end_time: '11:30',
    duration_hours: 2,
    pickup_location: 'Harry Reid International Airport',
    dropoff_location: 'Wynn Las Vegas',
    guest_count: 4,
    total_amount: 350,
    deposit_amount: 175,
    deposit_paid: true,
    status: 'confirmed',
    notes: 'Flight arrives 9:45am. Terminal 1. Meet at baggage claim.',
    created_at: '2026-02-22T08:00:00Z',
    updated_at: '2026-02-22T08:00:00Z',
  },
  {
    id: 'b8',
    quote_id: null,
    client_name: 'Samantha & Greg Wallace',
    client_email: 's.wallace@outlook.com',
    client_phone: '(818) 555-5555',
    event_type: 'Las Vegas Strip Tour',
    vehicle_id: '5',
    booking_date: '2026-03-12',
    start_time: '18:00',
    end_time: '21:00',
    duration_hours: 3,
    pickup_location: 'Bellagio',
    dropoff_location: 'Bellagio',
    guest_count: 6,
    total_amount: 475,
    deposit_amount: 200,
    deposit_paid: true,
    status: 'confirmed',
    notes: 'Anniversary Strip tour. Photo stops: Welcome sign, Bellagio fountains, Fremont.',
    created_at: '2026-02-18T12:00:00Z',
    updated_at: '2026-02-18T12:00:00Z',
  },
]

export const MOCK_ADMIN_TESTIMONIALS: Testimonial[] = [
  {
    id: 't1',
    name: 'Marcus T.',
    event_type: 'Bachelor Party',
    rating: 5,
    text: 'Absolute legends. The Sovereign party bus was insane — lights, sound, the whole vibe. Our group of 25 had the best night ever on the Strip.',
    is_featured: true,
    is_active: true,
    created_at: '2026-02-20T12:00:00Z',
  },
  {
    id: 't2',
    name: 'Jessica L.',
    event_type: 'Bachelorette Party',
    rating: 5,
    text: "We felt like actual royalty. The driver was amazing, the bus was spotless, and they even had champagne ready. 10/10 would book again!",
    is_featured: true,
    is_active: true,
    created_at: '2026-02-18T10:00:00Z',
  },
  {
    id: 't3',
    name: 'David & Sarah K.',
    event_type: 'Wedding',
    rating: 5,
    text: 'American Royalty handled all our wedding transportation flawlessly. The limos were beautiful and the drivers were incredibly professional.',
    is_featured: true,
    is_active: true,
    created_at: '2026-02-15T09:00:00Z',
  },
  {
    id: 't4',
    name: 'Chris R.',
    event_type: 'Corporate Event',
    rating: 5,
    text: 'Booked the Royal Sprinter for a client dinner. Impressed everyone. Professional, on time, and the vehicle was immaculate.',
    is_featured: false,
    is_active: true,
    created_at: '2026-02-10T08:00:00Z',
  },
  {
    id: 't5',
    name: 'Amanda P.',
    event_type: 'Birthday Celebration',
    rating: 5,
    text: 'My 30th birthday was EPIC thanks to American Royalty. The party bus was basically a club on wheels. Best birthday ever!',
    is_featured: true,
    is_active: true,
    created_at: '2026-02-08T14:00:00Z',
  },
  {
    id: 't6',
    name: 'Tyler M.',
    event_type: 'Nightlife & Club Crawl',
    rating: 5,
    text: 'Skip the taxis and Ubers. This is the only way to do Vegas nightlife. Our driver knew all the best spots and got us VIP everywhere.',
    is_featured: false,
    is_active: true,
    created_at: '2026-02-05T11:00:00Z',
  },
  {
    id: 't7',
    name: 'Karen W.',
    event_type: 'Prom & Homecoming',
    rating: 4,
    text: 'The kids had an amazing prom night! The driver was professional and patient with the teenagers. Felt safe knowing they were in good hands.',
    is_featured: false,
    is_active: true,
    created_at: '2026-01-28T16:00:00Z',
  },
  {
    id: 't8',
    name: 'Michael D.',
    event_type: 'Airport Transfer',
    rating: 4,
    text: 'Smooth airport pickup. Driver was waiting at baggage claim with a sign. The Sprinter was comfortable and clean. Will use again.',
    is_featured: false,
    is_active: false,
    created_at: '2026-01-20T10:00:00Z',
  },
]

// Helper to get vehicle name from ID
export function getVehicleName(vehicleId: string | null): string {
  const vehicles: Record<string, string> = {
    '1': 'The Sovereign',
    '2': 'The Crown Jewel',
    '3': 'Royal Sprinter',
    '4': 'The Monarch',
    '5': 'Black Diamond',
    '6': 'The Empire',
  }
  return vehicleId ? vehicles[vehicleId] || 'Unknown' : 'Not specified'
}

// Dashboard stats derived from mock data
export const DASHBOARD_STATS = {
  newQuotes: 3,
  pendingResponse: 1,
  quoted: 2,
  booked: 2,
  upcomingBookings: 6,
  monthlyRevenue: 8125,
}
